### ISSUE TITLE
Issue with multiple tarings

### ISSUE THREAD

**Issue by beeb** [DaneSlattery/hx711#1]
Hey there! Thanks a bunch for this library, it fits exactly what I needed.

I noticed a little problem, when calling the `tare()` function multiple times. It seems you use `read()` to get the value to be put as the offset, but `read()` itself already accounts for any previously existing `offset`.

So when performing the second tare, the weight is not reset to zero. Hope this makes sense!
You probably need a function that can get you the raw reading without applying the offset. Maybe the offset should only be applied in the `read_scaled()` function.

Thanks again!

PS: are you open to contributions?

**Comment by DaneSlattery** [comment]
Hi Beeb, I am open to contributions, but I am planning to fix this particular bug tonight and improve the documentation.

**Comment by beeb** [comment]
Awesome! Thanks. I'll keep using the lib and maybe make a PR if I find something that needs fixing. For now it's smooth sailing :)

**Comment by DaneSlattery** [comment]
PR done from my side, let me know if that addresses your needs!
