### ISSUE TITLE
Zero load cell readings become slightly off when reconnecting USB plug

### ISSUE THREAD

**Issue by weiying-chen** [DaneSlattery/hx711#16]
I'm using an ESP32-C3 and HX711 to read from a load cell. When I unplug and plug the USB cable, my load cell readings (without any load applied), become -1~-2 grams. Sometimes it happens, sometimes it doesn't. If I reset the ESP32-C3 with the Reset button or ESPMonitor, the readings become normal again. And they will only become abnormal if I unplug and plug the USB cable again.

Is this an known issue? Could it be related to how the crate initializes the scale?

Notes:

- I tried adding a 10 second delay before anything initializes to give the power time to stabilize, but the issue still persists. So maybe it's not a power-related.
- My ESP32-C3 connects to Wi-Fi before reading from the load cell. I'm not sure if that's related.

**Comment by DaneSlattery** [comment]
Hi Weiying-chen

Thank you for the inquiry. When you unplug the USB cable, does the esp32 die completely? 

1~2 grams doesn't seem like a lot, but I don't know the sensitivity of your load cell. Does your code `tare` during initialisation? It might be a tiny measurement error depending on your load cell sensitivity.

**Comment by weiying-chen** [comment]
Thanks for replying.

Yes, the ESP32 turns off completely. I'm using a 5 kg load cell. And I'm setting the scale to 0.0046. And yes, my code tares during initialization.

Any ideas what the issue could be?

**Comment by beeb** [comment]
That's about 0.02% error which is within the accuracy of load cells I could find online. Do you have accuracy information for your specific load cell?

**Comment by weiying-chen** [comment]
@beeb It's [this](https://www.tinytronics.nl/en/sensors/weight-pressure-force/load-cells/load-cell-5kg) one.

Maybe you're right. That's 0.02% accuracy. And it seems to be fine.

**Comment by weiying-chen** [comment]
Okay, sorry. I think this issue isn't related to the crate.
